require("mason-lspconfig").setup()

require("user.lsp.null-ls")
require("user.lsp.rust")
require("user.lsp.csharp")
require("user.lsp.python")
require("user.lsp.latex")
require("user.lsp.golang")
require("user.lsp.html")
require("user.lsp.css")
require("user.lsp.clangd")
require("user.lsp.sql")
require("user.lsp.kotlin")
